//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Sucursal = new HashSet<Sucursal>();
            this.Vendedor = new HashSet<Vendedor>();
        }
    
        public int idCiudad { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public int idProvincia { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
        [JsonIgnore]
        public virtual Provincia Provincia { get; set; }
        [JsonIgnore]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [JsonIgnore]
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        [JsonIgnore]
        public virtual ICollection<Vendedor> Vendedor { get; set; }
    }
}
