//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Compra
    {
        public Compra()
        {
            this.CompraDetalle = new HashSet<CompraDetalle>();
        }
    
        public int idCompra { get; set; }
        public int idProveedor { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
        public string NroFactura { get; set; }
        public Nullable<int> idMedioPago { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
        [JsonIgnore]
        public virtual ICollection<CompraDetalle> CompraDetalle { get; set; }
        [JsonIgnore]
        public virtual MedioPago MedioPago { get; set; }
    }
}
