//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bowtieEntities : DbContext
    {
        public bowtieEntities()
            : base("name=bowtieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CompraDetalle> CompraDetalle { get; set; }
        public virtual DbSet<Funcion> Funcion { get; set; }
        public virtual DbSet<FuncionXRol> FuncionXRol { get; set; }
        public virtual DbSet<GrupoProducto> GrupoProducto { get; set; }
        public virtual DbSet<GrupoXProducto> GrupoXProducto { get; set; }
        public virtual DbSet<Novedad> Novedad { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolxUsuario> RolxUsuario { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VentaDetalle> VentaDetalle { get; set; }
        public virtual DbSet<PromocionProducto> PromocionProducto { get; set; }
        public virtual DbSet<ProductoPrecio> ProductoPrecio { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<MedioPago> MedioPago { get; set; }
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<VentaPromoDetalle> VentaPromoDetalle { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Parametrizacion> Parametrizacion { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<productosWithStock> productosWithStock { get; set; }
    }
}
