//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class productosWithStock
    {
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> PrecioLista { get; set; }
        public Nullable<decimal> PrecioContado { get; set; }
        public string CodigoBarras { get; set; }
        public Nullable<int> Stock { get; set; }
        public int idStock { get; set; }
        public Nullable<decimal> PrecioGremio { get; set; }
    }
}
