//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Rol
    {
        public Rol()
        {
            this.FuncionXRol = new HashSet<FuncionXRol>();
            this.Novedad = new HashSet<Novedad>();
            this.RolxUsuario = new HashSet<RolxUsuario>();
        }
    
        public int idRol { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
        [JsonIgnore]
        public virtual ICollection<FuncionXRol> FuncionXRol { get; set; }
        [JsonIgnore]
        public virtual ICollection<Novedad> Novedad { get; set; }
        [JsonIgnore]
        public virtual ICollection<RolxUsuario> RolxUsuario { get; set; }
    }
}
